name: dart_web_scraper
description: Easy-to-use, reusable web scraper for scraping data. Extracts and cleans HTML/JSON, providing structured data results from web scraping. Ideal for scrapers looking for efficient ways to scrape and process web content.
version: 0.0.15
repository: https://github.com/sukhcha-in/dart_web_scraper

environment:
  sdk: ^3.3.1

dependencies:
  http: ^1.2.2
  html: ^0.15.4
  json5: ^0.8.0
  json_path: ^0.7.4
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
