name: dart_web_scraper
description: Config-based, reusable web scraper for web and API scraping. Scrape, parse web pages or APIs without writing parsers or scraping logic, using simple key/value based configs.
version: 0.1.4
repository: https://github.com/sukhcha-in/dart_web_scraper
issue_tracker: https://github.com/sukhcha-in/dart_web_scraper/issues
topics:
  - scraping
  - scraper
  - scrape

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.3.0
  html: ^0.15.5
  json5: ^0.8.0
  json_path: ^0.7.5
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
