name: dart_web_scraper
description: Config-based, reusable web scraper for web and API scraping. Scrape multiple pages or APIs without writing parsers or scraping logic, using simple configurations for efficient scraping.
version: 0.1.1
repository: https://github.com/sukhcha-in/dart_web_scraper
issue_tracker: https://github.com/sukhcha-in/dart_web_scraper/issues
topics:
  - scraping
  - scraper
  - scrape

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  html: ^0.15.4
  json5: ^0.8.0
  json_path: ^0.7.4
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
