name: dart_web_scraper
description: Easy-to-use, reusable web scraper. Extracts and cleans HTML/JSON, providing structured data results.
version: 0.0.8
repository: https://github.com/sukhcha-in/dart_web_scraper

environment:
  sdk: ^3.3.1

dependencies:
  http: ^1.1.0
  html: ^0.15.4
  json5: ^0.8.0
  json_path: ^0.7.2
  collection: ^1.19.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
